// <auto-generated />
namespace fyp_hunger_nd_spice_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class orderchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202305040059000_order changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
